(py3_venv) [ponnathan@pylab36b lessons]$ ipython
Python 3.11.6 (main, Oct  4 2023, 18:55:41) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from netmiko import ConnectHandler

In [2]: net_connect = ConnectHandler(host="cisco1.lasthop.ip", username="pyclass", password=getpass(), device_type="test"
   ...: )
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-594388a185ad> in <module>
----> 1 net_connect = ConnectHandler(host="cisco1.lasthop.ip", username="pyclass", password=getpass(), device_type="test"
      2 )

NameError: name 'getpass' is not defined

In [3]: from getpass import getpass

In [4]: net_connect = ConnectHandler(host="cisco1.lasthop.ip", username="pyclass", password=getpass(), device_type="test")
Password:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-67d0ce2d3082> in <module>
----> 1 net_connect = ConnectHandler(host="cisco1.lasthop.ip", username="pyclass", password=getpass(), device_type="test")

~/VENV/py3_venv/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py in ConnectHandler(*args, **kwargs)
    403         else:
    404             msg_str = telnet_platforms_str if "telnet" in device_type else platforms_str
--> 405         raise ValueError(
    406             "Unsupported 'device_type' "
    407             "currently supported platforms are: {}".format(msg_str)

ValueError: Unsupported 'device_type' currently supported platforms are:
a10
accedian
adtran_os
adva_fsp150f2
adva_fsp150f3
alaxala_ax26s
alaxala_ax36s
alcatel_aos
alcatel_sros
allied_telesis_awplus
apresia_aeos
arista_eos
arris_cer
aruba_aoscx
aruba_os
aruba_osswitch
aruba_procurve
audiocode_66
audiocode_72
audiocode_shell
avaya_ers
avaya_vsp
broadcom_icos
brocade_fastiron
brocade_fos
brocade_netiron
brocade_nos
brocade_vdx
brocade_vyos
calix_b6
casa_cmts
cdot_cros
centec_os
checkpoint_gaia
ciena_saos
cisco_apic
cisco_asa
cisco_ftd
cisco_ios
cisco_nxos
cisco_s200
cisco_s300
cisco_tp
cisco_viptela
cisco_wlc
cisco_xe
cisco_xr
cloudgenix_ion
coriant
dell_dnos9
dell_force10
dell_isilon
dell_os10
dell_os6
dell_os9
dell_powerconnect
dell_sonic
digi_transport
dlink_ds
eltex
eltex_esr
endace
enterasys
ericsson_ipos
ericsson_mltn63
ericsson_mltn66
extreme
extreme_ers
extreme_exos
extreme_netiron
extreme_nos
extreme_slx
extreme_tierra
extreme_vdx
extreme_vsp
extreme_wing
f5_linux
f5_ltm
f5_tmsh
fiberstore_fsos
flexvnf
fortinet
garderos_grs
generic
generic_termserver
hillstone_stoneos
hp_comware
hp_procurve
huawei
huawei_olt
huawei_smartax
huawei_vrp
huawei_vrpv8
ipinfusion_ocnos
juniper
juniper_junos
juniper_screenos
keymile
keymile_nos
linux
maipu
mellanox
mellanox_mlnxos
mikrotik_routeros
mikrotik_switchos
mrv_lx
mrv_optiswitch
netapp_cdot
netgear_prosafe
netscaler
nokia_srl
nokia_sros
oneaccess_oneos
ovs_linux
paloalto_panos
pluribus
quanta_mesh
rad_etx
raisecom_roap
ruckus_fastiron
ruijie_os
sixwind_os
sophos_sfos
supermicro_smis
teldat_cit
tplink_jetstream
ubiquiti_edge
ubiquiti_edgerouter
ubiquiti_edgeswitch
ubiquiti_unifiswitch
vertiv_mph
vyatta_vyos
vyos
watchguard_fireware
yamaha
zte_zxros
zyxel_os

In [5]: net_connect = ConnectHandler(host="cisco1.lasthop.ip", username="pyclass", password=getpass(), device_type="cisco_ios")
Password:
---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
~/VENV/py3_venv/lib/python3.11/site-packages/netmiko/base_connection.py in establish_connection(self, width, height)
   1141             try:
-> 1142                 self.remote_conn_pre.connect(**ssh_connect_params)
   1143             except socket.error as conn_error:

~/VENV/py3_venv/lib/python3.11/site-packages/paramiko/client.py in connect(self, hostname, port, username, password, pkey, key_filename, timeout, allow_agent, look_for_keys, compress, sock, gss_auth, gss_kex, gss_deleg_creds, gss_host, banner_timeout, auth_timeout, channel_timeout, gss_trust_dns, passphrase, disabled_algorithms, transport_factory, auth_strategy)
    376             # Try multiple possible address families (e.g. IPv4 vs IPv6)
--> 377             to_try = list(self._families_and_addresses(hostname, port))
    378             for af, addr in to_try:

~/VENV/py3_venv/lib/python3.11/site-packages/paramiko/client.py in _families_and_addresses(self, hostname, port)
    201         guess = True
--> 202         addrinfos = socket.getaddrinfo(
    203             hostname, port, socket.AF_UNSPEC, socket.SOCK_STREAM

/usr/local/lib/python3.11/socket.py in getaddrinfo(host, port, family, type, proto, flags)
    961     addrlist = []
--> 962     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    963         af, socktype, proto, canonname, sa = res

gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

NetmikoTimeoutException                   Traceback (most recent call last)
<ipython-input-5-478ac71f0357> in <module>
----> 1 net_connect = ConnectHandler(host="cisco1.lasthop.ip", username="pyclass", password=getpass(), device_type="cisco_ios")

~/VENV/py3_venv/lib/python3.11/site-packages/netmiko/ssh_dispatcher.py in ConnectHandler(*args, **kwargs)
    408         )
    409     ConnectionClass = ssh_dispatcher(device_type)
--> 410     return ConnectionClass(*args, **kwargs)
    411
    412

~/VENV/py3_venv/lib/python3.11/site-packages/netmiko/base_connection.py in __init__(self, ip, host, username, password, secret, port, device_type, verbose, global_delay_factor, global_cmd_verify, use_keys, key_file, pkey, passphrase, disabled_algorithms, disable_sha2_fix, allow_agent, ssh_strict, system_host_keys, alt_host_keys, alt_key_file, ssh_config_file, conn_timeout, auth_timeout, banner_timeout, blocking_timeout, timeout, session_timeout, read_timeout_override, keepalive, default_enter, response_return, serial_settings, fast_cli, _legacy_mode, session_log, session_log_record_writes, session_log_file_mode, allow_auto_change, encoding, sock, sock_telnet, auto_connect, delay_factor_compat, disable_lf_normalization)
    491         # Establish the remote connection
    492         if auto_connect:
--> 493             self._open()
    494
    495     def _open(self) -> None:

~/VENV/py3_venv/lib/python3.11/site-packages/netmiko/base_connection.py in _open(self)
    496         """Decouple connection creation from __init__ for mocking."""
    497         self._modify_connection_params()
--> 498         self.establish_connection()
    499         self._try_session_preparation()
    500

~/VENV/py3_venv/lib/python3.11/site-packages/netmiko/base_connection.py in establish_connection(self, width, height)
   1162
   1163                 msg = msg.lstrip()
-> 1164                 raise NetmikoTimeoutException(msg)
   1165             except paramiko.ssh_exception.AuthenticationException as auth_err:
   1166                 self.paramiko_cleanup()

NetmikoTimeoutException: DNS failure--the hostname you provided was not resolvable in DNS: cisco1.lasthop.ip:22

In [6]: net_connect = ConnectHandler(host="cisco1.lasthop.io", username="pyclass", password=getpass(), device_type="cisco_ios")
Password:

In [7]: net_connect.find_prompt()
Out[7]: 'cisco1#'

In [8]:
